[package]
name = "leetcode"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.*"
regex = "1.*"
itertools = "0.14.*"

[lints.clippy]
needless_range_loop = "allow"
if_same_then_else = "allow"
collapsible_else_if = "allow"
too_many_arguments = "allow"
comparison_chain = "allow"
