name: Check Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run Tests
        run: cargo test --verbose

  modules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Modules
        run: pip3 install natsort && ./scripts/update_main_mods.py && git diff --exit-code

  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Formatting
        run: ./scripts/format.sh && git diff --exit-code
      - name: Check Lints
        run: ./scripts/linting.sh
